### ISSUE TITLE
Luciphor2 support for mixed 64-bit and 32-bit data arrays in mzML files 

### ISSUE THREAD

**Issue by oliveralka** [dfermin/lucXor#2]
Hello,

I ran into an issue using the OpenMS LuciphorAdapter.
Following error occurred several times and the LuciphorAdapter failed:
```
 ERROR:QExactiveHF02_03926.mzML Scan: 12873
 # of mz values != # intensity values: 1830 != 457
 Skipping this scan...
```
This was related to the float precision of the m/z array and the intensity array (see below) and Luciphor2, which may only take 32-bit or 64-bit arrays [1].

We have a lot of files using a 64-bit float for the m/z array and a 32-bit float for the intensity array and this combination is commonly used in mzML-files, would it be possible to add that to luciphor? We can provide you a file if needed. 

[1] dfermin/lucXor@24c4b69

**Comment by dfermin** [comment]
Yes please send me a sample file to work on

Damian

Sent from my PDA. 
Please excuse typos & brevity.

**Comment by oliveralka** [comment]
Hello Damian,

here is dropbox link to a file for testing.  

https://www.dropbox.com/sh/c7167zmw1raxnty/AAAC7ZvofJl7zqXRfPoZ9XA6a?dl=0 <https://www.dropbox.com/sh/c7167zmw1raxnty/AAAC7ZvofJl7zqXRfPoZ9XA6a?dl=0>

If you have question or need something else, let me know. 

Thank you very much!

Cheers
Oliver

**Comment by dfermin** [comment]
Hi Oliver
Something is wrong with the Dropbox link you sent. When I try to use it I get a 404 error. 
Could you send it to me again? 

Also I’ve CC’d my collaborator on LuXor Dmitriy who will be helping to debug this issue.

Thanks,
Damian

**Comment by oliveralka** [comment]
Hello Damian,
I send you the right link to your google mail account, since I originally didn't want to post the link. 
I hope I found the right address, If you can't find it there please let me know! 

Cheers
Oliver

**Comment by dfermin** [comment]
Yes I looked in my email. You did send the link but it doesn't seem to work. Dmitry confirmed this as well. 

Could you send it again? Or perhaps upload it some other way?

Damian

Sent from my PDA. 
Please excuse typos & brevity.

**Comment by oliveralka** [comment]
Hello Damian,

sorry about that!
I zipped the file now and send you another Link! 

Cheers
Oliver

**Comment by oliveralka** [comment]
Hello Damian, 

have you been able to work with the file? 
If you need anything else, please do not hesitate to contact me. 

Oliver

**Comment by dfermin** [comment]
Hi Oliver

Sorry I've been out of communication.

Do you have another file you could send me?
The one you sent us didn't have any issues as far as I could tell.
I ran it through luXor and got no errors. I did it a while ago and
(obviously) didn't let you know.

Damian

**Comment by oliveralka** [comment]
Hello Damian,

no problem! 

I tested it with the luciphorAdapter in OpenMs - there the issue arises (see attachment).

In the [link](https://www.dropbox.com/sh/eb0v9ckhig4j4fk/AAAD6xsxGIuFcLxp9Toau-Zfa?dl=0) you will find the following files:
test_luciphor_64_32bit.mzml 
test_luciphor_32bit.mzml 
test_luciphor.idxml
test_luciphor_64_32bit.pepxml
test_luciphor_32bit.pepxml

If the precision is formatted mz: 64bit and int: 32bit (test_luciphor_64_32bit) the luciphorAdapter fails. If the precision is formatted the same mz & int 32 bit or 64 bit the Adapter finish without an issue (test_luciphor_32bit.mzml). 

That his why I suggested:
> This was related to the float precision of the m/z array and the intensity array (see below) and Luciphor2, which may only take 32-bit or 64-bit arrays [1].
> [1] dfermin/lucXor@24c4b69

I hope this helps! If you need another file format or other files please let me know! 

Here a screenshot:
![luciphor_error_64_32bit_mzml](https://cloud.githubusercontent.com/assets/15729190/23694974/2750e15a-03dd-11e7-8f8f-1f905fa4a488.png)

**Comment by dfermin** [comment]
Hi Oliver

I'm still working on this.
The person who wrote the mzML reader code is out of the country. I tried
reading their code but gave up. They should be back next week I hope.
Are you sure that OpenMS didn't change the Luciphor code to work with their
product?
I just want to have as much information to debug this going forward.

Damian

**Comment by oliveralka** [comment]
Hello Damian,

as far as I know the Luciphor code was not altered. The LuciphorAdapter is "just" a wrapper which writes a pepXML based on the idxml and mzml and forwards it to luciphor2 [1].

```
The following LuciPHOr2 version is required: luciphor2 (JAVA-based version of Luciphor) (1.2014Oct10). At the time of writing, it could be downloaded from http://luciphor2.sourceforge.net.
Input spectra for LuciPHOr2 have to be in pepXML file format. The input mzML file must be the same as the one used to create the pepXML input file.
```

[1] 
https://github.com/OpenMS/OpenMS/blob/7854aff8eca32d4e723553389316b18d7d7ca865/src/topp/LuciphorAdapter.cpp

**Comment by dfermin** [comment]
Hi Oliver

Sorry for the extremely late reply.

Can you try using this version of lucXor ?

http://dfermin.com/files/downloads/luciphorUpdate.zip

Damian

**Comment by oliveralka** [comment]
Hello Damian,

sorry for the late response! 

I get the following error message, when I try to run the LuciphorAdapter with the new version of lucXor:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
	at lucxor.LucXor.main(LucXor.java:54)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Maybe a dependency is missing? 

Oliver

**Comment by dfermin** [comment]
Okay.
Try that link again:

http://dfermin.com/files/downloads/luciphorUpdate.zip

This time the package should be there:
jar tf lucXor.jar

META-INF/MANIFEST.MF
lucxor/
lucxor/constants.class
lucxor/FLRClass.class
lucxor/globals.class
lucxor/LucXor.class
lucxor/ModelData_CID.class
lucxor/ModelData_HCD.class
lucxor/ModelParameterWorkerThread.class
lucxor/mzMLreader$1.class
lucxor/mzMLreader$SpectrumStruct.class
lucxor/mzMLreader.class
lucxor/NormalDensityWorkerThread.class
lucxor/PeakClass$1.class
lucxor/PeakClass$2.class
lucxor/PeakClass$3.class
lucxor/PeakClass$4.class
lucxor/PeakClass$5.class
lucxor/PeakClass.class
lucxor/Peptide.class
lucxor/PepXML.class
lucxor/PSM.class
lucxor/ScoringWorkerThread.class
lucxor/SpectrumClass.class
lucxor/statsFunctions.class
META-INF/
combinatoricslib-2.0.jar
commons-codec-1.8.jar
commons-collections-3.2.1.jar
commons-lang3-3.2.1.jar
commons-math3-3.2.jar
guava-15.0.jar
hotsax.jar
junit.jar
MSDataStructures.jar
trove-3.0.3.jar

**Comment by oliveralka** [comment]
Hello Damian, 

I still get the error, even when started from the command line:
New version: 
```
u-082-c025:luciphor_fix_1 alka$ java -jar luciphor2.jar 

luciphor2 (JAVA-based version of Luciphor)
Version: 1.2014Oct10
Original C++ version available at: http://luciphor.sf.net

USAGE: java -jar luciphor2.jar <input_file>

	Generate a luciphor2 input file with: java -jar luciphor2.jar -t
	Modify the input file to suit your needs and submit it to the program.
	Example: java -jar luciphor2.jar input_file_you_edited

u-082-c025:luciphor_fix_1 alka$ java -jar luciphor2.jar -t

luciphor2 (JAVA-based version of Luciphor)
Version: 1.2014Oct10
Original C++ version available at: http://luciphor.sf.net

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
	at lucxor.LucXor.main(LucXor.java:49)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
For comparison old version:
```
u-082-c025:luciphor alka$ java -jar luciphor2.jar 

luciphor2 (JAVA-based version of Luciphor)
Version: 1.2014Oct10
Original C++ version available at: http://luciphor.sf.net

USAGE: java -jar luciphor2.jar <input_file>

	Generate a luciphor2 input file with: java -jar luciphor2.jar -t
	Modify the input file to suit your needs and submit it to the program.
	Example: java -jar luciphor2.jar input_file_you_edited

u-082-c025:luciphor alka$ java -jar luciphor2.jar -t

luciphor2 (JAVA-based version of Luciphor)
Version: 1.2014Oct10
Original C++ version available at: http://luciphor.sf.net


Please edit the input file: luciphor2_input_template.txt with your favorite text editor
```

**Comment by dfermin** [comment]
This is weird.

I've tested the latest jar I sent you on 3 different machines (linux,
windows, macos) none of these machines had a previous installation of the
lucXor.jar or it's dependencies.

That jar file worked without issues on all 3 machines.
As I mentioned in the previous email the guava library is definitely
contained in the jar file.

Are you altering your classpath some how?
Are you using an out of date version of java? I compile/use version
1.8.0_121-b13. So you need to use at least version 1.8.0 java.

The sample output indicates you renamed the jar from lucXor.jar to
luciphor2.jar. Are you sure you are calling the right file?


Damian

**Comment by oliveralka** [comment]
Hi Damian,

i previously renamed the lucXor.jar to luciphor2.jar - for the TOPPAS workflow. 
Just for testing I downloaded your update again and get the same results. 

Java-version:
```
unicorn:Downloads alka$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
Test not renamed file:

```
unicorn:Downloads alka$ java -jar lucXor.jar 

luciphor2 (JAVA-based version of Luciphor)
Version: 1.2014Oct10
Original C++ version available at: http://luciphor.sf.net

USAGE: java -jar luciphor2.jar <input_file>

	Generate a luciphor2 input file with: java -jar luciphor2.jar -t
	Modify the input file to suit your needs and submit it to the program.
	Example: java -jar luciphor2.jar input_file_you_edited
```
-> this should be java -jar lucXor.jar -t in this case or? 

```
unicorn:Downloads alka$ java -jar lucXor.jar -t

luciphor2 (JAVA-based version of Luciphor)
Version: 1.2014Oct10
Original C++ version available at: http://luciphor.sf.net

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
	at lucxor.LucXor.main(LucXor.java:49)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

Not sure if I do something wrong? 
I can hopefully test it tomorrow on another machine.
I am using osx 10.12.

Cheers

**Comment by dfermin** [comment]
Try this: jar tf lucXor.jar | grep -i 'com/google/common/collect/Multimap'

This should list the contents of the jar specifically highlighting the
class files for the multiMap you can't find.  On my end it lists the
Multimap.class file, so it's in the jar.  If you don't see it there then
somewhere along the way the library is being lost some how.

The other possibility is that your java classpath is being altered in
someway. I'm not sure how though.

Damian

**Comment by oliveralka** [comment]
This is the whole output without the grep command:

```
unicorn:Downloads alka$ jar tf lucXor.jar 
META-INF/MANIFEST.MF
lucxor/
lucxor/constants.class
lucxor/FLRClass.class
lucxor/globals.class
lucxor/LucXor.class
lucxor/ModelData_CID.class
lucxor/ModelData_HCD.class
lucxor/ModelParameterWorkerThread.class
lucxor/mzMLreader$1.class
lucxor/mzMLreader$SpectrumStruct.class
lucxor/mzMLreader.class
lucxor/NormalDensityWorkerThread.class
lucxor/PeakClass$1.class
lucxor/PeakClass$2.class
lucxor/PeakClass$3.class
lucxor/PeakClass$4.class
lucxor/PeakClass$5.class
lucxor/PeakClass.class
lucxor/Peptide.class
lucxor/PepXML.class
lucxor/PSM.class
lucxor/ScoringWorkerThread.class
lucxor/SpectrumClass.class
lucxor/statsFunctions.class
META-INF/
combinatoricslib-2.0.jar
commons-codec-1.8.jar
commons-collections-3.2.1.jar
commons-lang3-3.2.1.jar
commons-math3-3.2.jar
guava-15.0.jar
hotsax.jar
junit.jar
MSDataStructures.jar
trove-3.0.3.jar
```
With your grep command it seems that nothing is found:

```
unicorn:Downloads alka$ jar tf lucXor.jar | grep -i 'com/google/common/collect/Multimap'
unicorn:Downloads alka$ 
```

Oliver

**Comment by dfermin** [comment]
Okay so the multimap library isn't there.
I've just recreated the link with the copy of the jar file on my local
machine.
Try the download again.

This time type:
md5sum luciphorUpdate.zip

the resulting output should be: d29bcce5c4ae92060a6b6cefb495ffea

If it is then the download should be good and work.
unzip the archive and try running the jar file.

Damian

**Comment by oliveralka** [comment]
Seems to work fine now! 

```
unicorn:Downloads alka$ md5 luciphorUpdate.zip 
MD5 (luciphorUpdate.zip) = d29bcce5c4ae92060a6b6cefb495ffea
```

```
unicorn:Downloads alka$ java -jar lucXor.jar -t

luciphor2 (JAVA-based version of Luciphor)
Version: 1.2014Oct10
Original C++ version available at: http://luciphor.sf.net

Please edit the input file: luciphor2_input_template.txt with your favorite text editor
```
I will test it tomorrow with the 64/32 bit files in the LuciphorAdapter.
Thank you very much for your help!

Oliver

**Comment by oliveralka** [comment]
Hello Damian,
 the new version works for 32bit & 64bit float precision but unfortunately not for the mixed version 64bit_32bit. 
The same error as shown above occures:
```
 ERROR:QExactiveHF02_03926.mzML Scan: 12873
 # of mz values != # intensity values: 1830 != 457
 Skipping this scan...
```
I made another dropbox link with the input (mzml, idxml, pepxml) & output files (idxml). 
Link: https://www.dropbox.com/sh/4ottvb2d2eh7daw/AAAjtpKu4fgBd98-jnMomgO9a?dl=0

May you have look on it?

Thanks
Oliver

**Comment by dfermin** [comment]
I'll look at this again with your files.
But first can you run PeptideProphet on your pepXML files?
There are no probabilities in your pepXML files because the final command
hasn't been run. Without this Luciphor can't score the spectra. My
debugging has been on in house mzML files I have that are 64 bit.

Damian

**Comment by oliveralka** [comment]
Thank you for pointing that out - there seem to be an issue with selecting the right score. I will work on that.

To work with the data and reproduce the issue we are having using mixed 64bit/32bit precision as stated above - you could use the hack: Setting the modeling_score_threshold to 0. (I know it is not supposed to be used that way - but until I fixed the score - you could have a look on it). 

Oliver

**Comment by oliveralka** [comment]
Hello Damian,

I updated the files - the pepXML should now contain the probabilities. 

Please have a look! 

Link: https://www.dropbox.com/sh/4ottvb2d2eh7daw/AAAjtpKu4fgBd98-jnMomgO9a?dl=0

**Comment by dfermin** [comment]
Okay the link has been updated and it did run to completion with your
sample files.
Download the luciphorUpdate.zip file again and give it a go.

Damian

**Comment by oliveralka** [comment]
Hello Damian,

unfortunately the link doesn't seem to work. 

Cheers
Oliver

**Comment by dfermin** [comment]
Try it again. My webserver went down and I hadn't noticed (sorry)


http://dfermin.com/files/downloads/luciphorUpdate.zip

**Comment by oliveralka** [comment]
The files with mixed precision (64/32bit) work with your new version.

Thank you very much! 

Cheers
Oliver

**Comment by oliveralka** [comment]
Hi Damian, 

I recently tried to run luciphor2 with a newer java version using our test in OpenMS. 

1) Everything works fine for Java8, trying Java13 I get the following error:

---
Reading spectra from /Users/alka/Desktop/LuciPhor/current_test  (MZML format)
This can take a while so please be patient.

LuciphorAdapter_1_input.mzML:  Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at umich.ms.fileio.filetypes.mzml.MZMLFile.parseRunInfo(MZMLFile.java:91)
	at umich.ms.fileio.filetypes.AbstractLCMSDataSource.fetchRunInfo(AbstractLCMSDataSource.java:74)
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parseScan(AbstractXMLBasedDataSource.java:640)
	at lucxor.globals.read_mzML(globals.java:652)
	at lucxor.globals.read_in_spectra(globals.java:622)
	at lucxor.LucXor.main(LucXor.java:71)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more

Exit code: 1
LuciphorAdapter took 2.74 s (wall), 1.48 s (CPU), 0.03 s (system), 1.45 s (user).
—

If found some references in regard to 
"java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException” 

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j <https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j>
The JAXB APIs are considered to be Java EE APIs and therefore are no longer contained on the default classpath in Java SE 9

Would you be able to take a look here? 


2) I have an additional off-topic question about handling .mzML:

If you would like to process one mzML file (1.mzML) and have the pepXML for the specific file. 
The 1.mzML is in a directory with some other mzML files (e.g. 2.mzML - 20.mzML). 
How does Luciphor2 references the correct .mzML to be processed? 
Via the name of the pepXML, or the file referenced in the pepXML? 
Since it will only process the file, which also has a valid pepXML - I assume. 

Thank you very much!

With kind regards 
Oliver

**Comment by dfermin** [comment]
I have to find time to update the code to run with Java 13.
In the mean time use Java 8. 

Regarding the second question, Luciphor2 extracts the file name from the scan ID in the pepXML file. So if your scanID in the pepXML file is `somefile.001.001.03` then you need to provide it the path to `somefile.mzML`.

**Comment by oliveralka** [comment]
Thanks a lot for the explanation and having a look! 

Sorry for reopening this issue - if you like I can open one - specific for the Java 13 question (which may be easier to find for others.)

Let me know if you have any other questions or something ready to test down the road!

**Comment by chhh** [comment]
@dfermin In theory it should be enough to update MSFTBX library to a newer version. It had Java 9+ compatibility for quite a while now.

**Comment by dfermin** [comment]
@chhh has fixed the problem. 
If you download the mavenize branch of luciphor and run `mvn clean package` in the root directory you will get a working jar at `lucxor/target/lucxor-2.1-SNAPSHOT.one-jar.jar`

Thanks @chhh !

**Comment by oliveralka** [comment]
Tested in #4
