### ISSUE TITLE
Mavenized Luciphor2 "release"

### ISSUE THREAD

**Issue by oliveralka** [dfermin/lucXor#5]
Hi Damian, 

would it be possible to get a "release" for the mavenized version of luciphor2 to facilitate the availability in bioconda? 

I think the current sourceforge download link points to the non mavenized version. 
https://sourceforge.net/projects/luciphor2/files/luciphor2.jar/download?use_mirror=master

See https://github.com/OpenMS/OpenMS/issues/4622

Thank you!

**Comment by dfermin** [comment]
Hi
Just uploaded a new luciphor JAR to source forge. It's called luciphor2_1.jar
This is the latest maven-built version.

**Comment by chhh** [comment]
@dfermin I think you should upload the release here on github as well (https://github.com/dfermin/lucXor/releases)
