### ISSUE TITLE
Line of code explanation 

### ISSUE THREAD

**Issue by ypriverol** [dfermin/lucXor#7]
@dfermin: 

I have been trying to update the tool (dependencies, output, etc). I'm trying to understand the code in addition. I have found a line that is interesting because it sorts a list descending and then ascending. 

https://github.com/dfermin/lucXor/blob/70f846afc2a5cff2dfd9c3e58bd05724f30eb96a/src/lucxor/PSM.java#L582

I have tried to remove the first sorting and the results are the same because the second line is the one that has an effect. Can you clarify on this? 

Thanks a lot in advance.

**Comment by dfermin** [comment]
If the results are the same then the just keep the second line.
