### ISSUE TITLE
Gold standard test 

### ISSUE THREAD

**Issue by ypriverol** [dfermin/lucXor#8]
@dfermin: 

Do you have or keep an example dataset (it can be from the papers) that we can use for testing, It would be great if is a small sample. 

The idea would be if someone does some changes in the algorithm (performance, refactoring, etc) we know that the final results haven't been changed.

**Comment by dfermin** [comment]
You could try the original data used in the Luciphor 1 publication. 
That should still be available on source forge at: http://luciphor.sourceforge.net

**Comment by ypriverol** [comment]
Thanks!!!!
